name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout deploy
      uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build container image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: docker build -t registry.digitalocean.com/ethfoundation/tldr_bot:$IMAGE_TAG .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: docker push registry.digitalocean.com/ethfoundation/tldr_bot:$IMAGE_TAG

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ethfoundation

    - name: Deploy to DigitalOcean Kubernetes
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i.bak "s|tldr_bot:.*|${IMAGE_TAG}|g" k8s/bot.yaml  # Update the image tag in the deployment file
        kubectl apply -f k8s/postgres-pv.yaml
        kubectl apply -f k8s/postgres.yaml
        kubectl apply -f k8s/bot.yaml
        echo "Deployment complete with image ${IMAGE_TAG}"
